# Page-state cache, row-deduplicated: oracle-captured pages -> ROM data + gen/bgdata.h
#   tiles: 32-byte planar tiles, 512 per bank           (cell id = 1024 + tile index)
#   rows : 26 x u16 cell ids (52 B), 256 per bank
#   maps : 17 x u16 row ids (34 B), 256 per bank
#   keys : sorted (u32 key, u16 map index) 6 B each, filter bitmap (2 KB) at 0x3800 of the key bank
import numpy as np, struct, sys, glob
BANK=16384; B0=int(sys.argv[1]) if len(sys.argv)>1 else 150
W,H,CW,CH=208,136,26,17
XS=np.floor((np.arange(W)+0.5)*320/W).astype(int); YS=np.floor((np.arange(H)+0.5)*200/H).astype(int)
def planar(t):
    out=bytearray()
    for row in t:
        for p in range(4):
            b=0
            for x in range(8): b|=((int(row[x])>>p)&1)<<(7-x)
            out.append(b)
    return bytes(out)
pages={}
for fn in sorted(glob.glob('/home/claude/w/cap/pc_*.bin')):
    if fn.endswith('pc_all.bin'): continue
    b=open(fn,'rb').read()
    for i in range(len(b)//64004):
        k=struct.unpack('<I',b[i*64004:i*64004+4])[0]
        if k not in pages: pages[k]=np.frombuffer(b[i*64004+4:(i+1)*64004],np.uint8).reshape(200,320)
tiles={}; tdata=bytearray(); rows={}; maps=[]
for k in sorted(pages):
    im=pages[k][YS][:,XS]; tl=im.reshape(CH,8,CW,8).transpose(0,2,1,3).reshape(CH,CW,8,8)
    rids=[]
    for r in range(CH):
        ids=[]
        for c in range(CW):
            t=tl[r,c]
            if (t==t[0,0]).all(): ids.append(int(t[0,0])); continue
            key=t.tobytes()
            if key not in tiles: tiles[key]=len(tiles); tdata+=planar(t)
            ids.append(1024+tiles[key])
        rids.append(rows.setdefault(tuple(ids),len(rows)))
    maps.append((k,rids))
assert 1024+len(tiles) < 0x8000
def pad(b): return b+b'\0'*((-len(b))%BANK)
tblob=pad(tdata)
rblob=pad(b''.join(b''.join([struct.pack('<26H',*r) for r in list(rows)[i:i+256]]).ljust(BANK,b'\0') for i in range(0,len(rows),256)))
rowlist=sorted(rows,key=lambda r:rows[r])
rblob=b''.join(b''.join(struct.pack('<26H',*r) for r in rowlist[i:i+256]).ljust(BANK,b'\0') for i in range(0,len(rowlist),256))
mblob=b''.join(b''.join(struct.pack('<17H',*m) for _,m in maps[i:i+256]).ljust(BANK,b'\0') for i in range(0,len(maps),256))
keys=sorted((k,i) for i,(k,_) in enumerate(maps))
PER=2730                                   # 6-byte entries per key bank (no entry crosses a bank)
kbanks=[keys[i:i+PER] for i in range(0,len(keys),PER)]
assert len(kbanks)<=16
bm=bytearray(2048)
for k,_ in keys:
    j=((k>>16)^k)&0x3FFF; bm[j>>3]|=1<<(j&7)
# filter bank: bitmap (2 KB), then count of key banks, entries per bank (u16) and first key (u32) of each
fb=bytearray(bm)+bytes([len(kbanks)])+b''.join(struct.pack('<HI',len(kb),kb[0][0]) for kb in kbanks)
fblob=bytes(fb).ljust(BANK,b'\0')
kblob=b''.join(b''.join(struct.pack('<IH',k,i) for k,i in kb).ljust(BANK,b'\0') for kb in kbanks)
TB=B0; RB=TB+len(tblob)//BANK; MB=RB+len(rblob)//BANK; FB=MB+len(mblob)//BANK; KB=FB+1
blob=tblob+rblob+mblob+fblob+kblob
open('/home/claude/w/sms/gen/bg.bin','wb').write(blob)
open('/home/claude/w/sms/gen/bgdata.h','w').write('/* generated by mkbg.py: row-deduplicated pre-rendered page states */\n'
  '#define NBG %d\n#define BGT_BANK0 %d\n#define BGR_BANK0 %d\n#define BGM_BANK0 %d\n#define BGF_BANK %d\n#define BGK_BANK %d\n'%(len(keys),TB,RB,MB,FB,KB))
print('%d states, %d tiles, %d rows; banks tiles %d-%d rows %d-%d maps %d-%d filter %d keys %d-%d (end %d)'%(len(keys),len(tiles),len(rows),TB,RB-1,RB,MB-1,MB,FB-1,FB,KB,KB+len(kbanks)-1,KB+len(kbanks)-1))
assert KB+len(kbanks)-1<=255, 'ROM full'
