# Move large constant tables out of the fixed code banks into ROM bank CONST_BANK (run after mkgame.py).
# Extracts pal_sms, font8, sfx_tab (gen/gamedata.h) and demo_in (gen/demo_input.h, if present),
# writes gen/const.bin + gen/constdata.h (pointer macros), and strips the arrays from the headers.
import re, struct, sys
BANK=13; G='/home/claude/w/sms/gen/'
def grab(fn, name):
    s=open(fn).read()
    m=re.search(r'static const (\w+) %s(\[[^=]*)=\s*\{'%name, s)
    if not m: return None, s
    i=m.end(); depth=1
    while depth: depth+=(s[i]=='{')-(s[i]=='}'); i+=1
    body=s[m.end():i-1]; end=s.index(';',i)+1
    vals=[int(v,0) for v in re.findall(r'0x[0-9A-Fa-f]+|\d+', body)]
    return (m.group(1), vals), s[:m.start()]+'/* %s moved to ROM bank %d (constdata.h) */'%(name,BANK)+s[end:]
blob=bytearray(); defs=['/* generated by mkconst.py */','#define CONST_BANK %d'%BANK]
for fn,name,macro,ctype in ((G+'gamedata.h','pal_sms','PAL_SMS','(const uint8_t *)'),
                            (G+'gamedata.h','font8','FONT8','(const uint8_t *)'),
                            (G+'gamedata.h','sfx_tab','SFX_TAB','(const uint8_t *)'),
                            (G+'gamedata.h','bbox_tab','BBOX_TAB','(const uint8_t *)'),
                            (G+'demo_input.h','demo_in','DEMO_IN','(const uint16_t *)')):
    try: r,s=grab(fn,name)
    except FileNotFoundError: continue
    if r is None: continue
    t,vals=r
    defs.append('#define %s (%s(0x8000 + %d))'%(macro,ctype,len(blob)))
    defs.append('#define %s_ADDR 0x%04X'%(macro,0x8000+len(blob)))
    blob+=b''.join(struct.pack('<H' if t in ('uint16_t','int16_t') else '<B', v & (0xFFFF if t in ('uint16_t','int16_t') else 0xFF)) for v in vals)
    open(fn,'w').write(s)
# bbox_tab index at 0xB000: first table entry per (segment 1/2, offset high byte), 513 u16 (bbox_find narrows
# its binary search to that bucket: ~3.7k -> ~0.6k cycles per lookup)
if any(d.startswith('#define BBOX_TAB_ADDR') for d in defs):
    a=int([d for d in defs if d.startswith('#define BBOX_TAB_ADDR')][0].split()[-1],16)-0x8000
    n=[int(l.split()[2]) for l in open(G+'gamedata.h') if l.startswith('#define NBBOX')][0]
    keys=[(blob[a+12*i+2],blob[a+12*i]|(blob[a+12*i+1]<<8)) for i in range(n)]; assert keys==sorted(keys)
    import bisect
    idx=[bisect.bisect_left(keys,(1 if k<256 else 2,(k&255)<<8)) for k in range(512)]+[n]
    assert len(blob)<=0x3000; blob+=b'\xff'*(0x3000-len(blob)); blob+=struct.pack('<513H',*idx)
    defs.append('#define BBOX_IDX_ADDR 0xB000')
assert len(blob)<=16384
open(G+'const.bin','wb').write(bytes(blob)); open(G+'constdata.h','w').write('\n'.join(defs)+'\n')
print('const blob %d bytes in bank %d'%(len(blob),BANK)); print('\n'.join(defs))
