# recorded route input (cap/solution_16002.txt: "frame mask" hex) -> gen/demo_input.h for -DDEMOPLAY builds
rows=[l.split() for l in open('/home/claude/w/cap/solution_16002.txt') if l.strip()]
ent=sorted((int(f),int(m,16)) for f,m in rows)
open('/home/claude/w/sms/gen/demo_input.h','w').write(
  '/* generated by mkdemo.py: recorded input for part 16002 (frame, AW mask: 1 R, 2 L, 4 D, 8 U, 0x80 action) */\n'
  '#define NDEMO %d\nstatic const uint16_t demo_in[NDEMO][2] = {%s};\n'%(len(ent),','.join('{%d,0x%02X}'%e for e in ent)))
print('demo input: %d entries'%len(ent))
