# Flattened shape hierarchies for zoom-64 draws (run after mkconst.py; needs gen/game.bin + gen/const.bin).
# At zoom 64 every child position in a hierarchy is a plain integer sum of the header offsets, so a shape
# expands to a fixed, ordered list of leaves (polygon or bitmap mask) with positions relative to the anchor.
# The engine draws that list instead of walking the tree (pfetch + recursion per node).
#   directory at FLAT_BANK0:0x8000: NBBOX x (bank, addr lo, addr hi); bank 0 = not flattened (walk as before)
#   list: count, then count x 8 bytes: kind (0 poly, 1 mask), color, off/num (u16), dx (s16), dy (s16)
import re, struct
G='/home/claude/w/sms/gen/'; BANK=16384
def define(fn, name):
    return int(re.search(r'#define %s\s+(\S+)'%name, open(G+fn).read()).group(1), 0)
FLAT_BANK0=14
game=open(G+'game.bin','rb').read(); B0=2
seg_base={1: (define('gamedata.h','V1_BANK')-B0)*BANK, 2: (define('gamedata.h','V2_BANK')-B0)*BANK}
nbbox=define('gamedata.h','NBBOX'); ba=define('constdata.h','BBOX_TAB_ADDR')-0x8000
const=open(G+'const.bin','rb').read()
keys=[(const[ba+12*i+2], const[ba+12*i]|(const[ba+12*i+1]<<8)) for i in range(nbbox)]
def walk(seg, off, color, x, y, out):        # mirrors draw_shape / draw_shape_parts at zoom 64
    d=game[seg_base[seg]:]; i=d[off]; off+=1
    if i>=0xC0:
        if color&0x80: color=i&0x3F
        out.append((0,color,off,x,y))
    elif (i&0x3F)==2:
        ptx=x-d[off]; pty=y-d[off+1]; n=d[off+2]; off+=3
        for _ in range(n+1):                  # n read as a byte into an int16 loop: n+1 children
            o=(d[off]<<8)|d[off+1]; pox=ptx+d[off+2]; poy=pty+d[off+3]; off+=4; c=0xFF
            if o&0x8000:
                c=d[off]; num=d[off+1]; off+=2
                if c&0x80: out.append((1,c&0x7F,num,pox,poy)); continue
                c&=0x7F
            walk(seg,(o<<1)&0xFFFF,c,pox,poy,out)
dirb=bytearray(); lists=bytearray(); nflat=nleaf=0; maxn=0
DIR=3*nbbox
for seg,off in keys:
    d=game[seg_base[seg]:]
    if (d[off]&0x3F)!=2 or d[off]>=0xC0: dirb+=b'\0\0\0'; continue
    out=[]; walk(seg,off,0xFF,0,0,out)
    assert len(out)<256
    rec=bytes([len(out)])+b''.join(struct.pack('<BBHhh',*l) for l in out)
    pos=DIR+len(lists)
    if pos//BANK!=(pos+len(rec)-1)//BANK: lists+=b'\0'*(BANK-pos%BANK); pos=DIR+len(lists)
    dirb+=struct.pack('<BH',FLAT_BANK0+pos//BANK,0x8000+pos%BANK); lists+=rec
    nflat+=1; nleaf+=len(out); maxn=max(maxn,len(out))
blob=bytes(dirb)+bytes(lists); blob+=b'\0'*((-len(blob))%BANK)
open(G+'flat.bin','wb').write(blob)
open(G+'flatdata.h','w').write('/* generated by mkflat.py */\n#define FLAT_BANK0 %d\n#define FLAT_DIR_ADDR 0x8000\n'%FLAT_BANK0)
print('flat: %d of %d shapes are hierarchies, %d leaves (max %d), %d bytes, banks %d..%d'%(nflat,nbbox,nleaf,maxn,len(dirb)+len(lists),FLAT_BANK0,FLAT_BANK0+len(blob)//BANK-1))
