# Build game data: part 16002 resources in ROM banks + gen/gamedata.h (tables compiled into the fixed code).
import sys, struct, re, math
sys.path.insert(0,'/home/claude/w/audio')
from psgconv import *
BANK=16384
res=load_resources(); S=samples_of(res)
PART=(0x1A,0x1B,0x1C,0x11)  # palette, bytecode, video1, video2
BANK0=2
blob=bytearray(); H=['/* generated by mkgame.py */','#include <stdint.h>']
def align():
    global blob
    if len(blob)%BANK: blob+=b'\0'*(BANK-len(blob)%BANK)
def place(name,data):
    align(); b=BANK0+len(blob)//BANK; blob.extend(data); H.append('#define %s_BANK %d'%(name,b)); return b
place('BC',res[PART[1]][1]); place('V1',res[PART[2]][1]); place('V2',res[PART[3]][1])
H.append('#define BC_SIZE %d'%len(res[PART[1]][1]))
# palettes (Amiga/VGA 12-bit) -> SMS
pal=res[PART[0]][1]; LV=[0,0,0,1,1,1,1,1,2,2,2,2,2,3,3,3]
rows=[]
for p in range(32):
    cs=[]
    for i in range(16):
        c=struct.unpack('>H',pal[(p*16+i)*2:(p*16+i)*2+2])[0]
        cs.append(LV[(c>>8)&15]|(LV[(c>>4)&15]<<2)|(LV[c&15]<<4))
    rows.append('{'+','.join('0x%02X'%x for x in cs)+'}')
H.append('static const uint8_t pal_sms[32][16]={'+',\n'.join(rows)+'};')
# initial vars (state handed over by the intro)
v=struct.unpack('<256h',open('/home/claude/w/cap/vars_16002_start.bin','rb').read())
nz=[(i,x) for i,x in enumerate(v) if x]
H.append('#define NINITVARS %d'%len(nz))
H.append('static const uint8_t initvar_idx[]={%s};'%','.join(str(i) for i,_ in nz))
H.append('static const int16_t initvar_val[]={%s};'%','.join(str(x) for _,x in nz))
# font + strings from rawgl static data
src=open('/home/claude/w/rawgl/staticres.cpp').read()
m=re.search(r'const uint8_t Graphics::_font\[\] = \{(.*?)\};',src,re.S)
font=[int(x,16) for x in re.findall(r'0x([0-9A-Fa-f]+)',m.group(1))]
H.append('static const uint8_t font8[%d]={%s};'%(len(font),','.join(str(x) for x in font)))
m=re.search(r'const StrEntry Video::_stringsTableEng\[\] = \{(.*?)\n\};',src,re.S)
strs={}
for sid,st in re.findall(r'\{\s*(0x[0-9A-Fa-f]+|\d+),\s*"((?:[^"\\]|\\.)*)"\s*\}',m.group(1)): strs[int(sid,0)]=st
m=re.search(r'const StrEntry Video::_stringsTableDemo\[\] = \{(.*?)\n\};',src,re.S)
for sid,st in re.findall(r'\{\s*(0x[0-9A-Fa-f]+|\d+),\s*"((?:[^"\\]|\\.)*)"\s*\}',m.group(1)): strs.setdefault(int(sid,0),st)
used=sorted(set(int(x,16) for x in re.findall(r'drawString\(str=0x([0-9A-F]+)',open('/home/claude/w/cy/ootwdemo_16002.bytecode.txt').read())))
H.append('#define NSTRINGS %d'%len(used))
H.append('static const uint16_t str_id[]={%s};'%','.join(str(i) for i in used))
H.append('static const char * const str_txt[]={%s};'%','.join('"%s"'%strs[i] for i in used))
# 1991 DOS sprite masks
mo=re.search(r'const uint16_t Graphics::_shapesMaskOffset\[\] = \{(.*?)\};',src,re.S)
md=re.search(r'const uint8_t Graphics::_shapesMaskData\[\] = \{(.*?)\};',src,re.S)
offs=[int(x,0) for x in re.findall(r'0x[0-9A-Fa-f]+|\d+',mo.group(1))]
data=bytes(int(x,0) for x in re.findall(r'0x[0-9A-Fa-f]+|\d+',md.group(1)))
place('MASK',data); H.append('#define NMASKS %d'%len(offs))
H.append('static const uint16_t mask_off[]={%s};'%','.join(str(x) for x in offs))
# coordinate LUTs: AW 320x200 -> 208x136
XMIN,XMAX,YMIN,YMAX=-512,1023,-384,639
H.append('#define LUTX_MIN %d\n#define LUTX_MAX %d\n#define LUTY_MIN %d\n#define LUTY_MAX %d'%(XMIN,XMAX,YMIN,YMAX))
lut=struct.pack('<%dh'%(XMAX-XMIN+1),*[math.floor(x*13/20) for x in range(XMIN,XMAX+1)])+struct.pack('<%dh'%(YMAX-YMIN+1),*[math.floor(y*17/25) for y in range(YMIN,YMAX+1)])
place('LUT',lut); H.append('#define LUTY_OFF %d'%(2*(XMAX-XMIN+1)))
# reciprocal table for the edge stepper
H.append('static const uint16_t recip[256]={%s};'%','.join(str(0x4000//max(d,1)) for d in range(256)))
# volume attenuation offsets for script volume 0..63
H.append('static const uint8_t volatt[64]={%s};'%','.join(str(15 if v==0 else min(15,int(round(-20*math.log10(v/63)/2)))) for v in range(64)))
# SFX: every (res,freq) in the part's bytecode -> PSG tick stream (u16/tick: bit15 noise, bits14..11 att, bits9..0 period/mode)
pairs=sorted(set((int(r),int(f)) for r,f in re.findall(r'playSound\(res=(\d+), freq=(\d+)',open('/home/claude/w/cy/ootwdemo_16002.bytecode.txt').read())))
ent=[]; sfxblob=bytearray()
for r,f in pairs:
    if r not in S: continue
    smp=S[r]; rate=sfx_rate(f); vc=Voice(smp,rate,64,0)
    words=[]; loop_at=None; t=0
    while True:
        out=vc.render(t)
        if out is None: break
        pos=t*rate/60
        if smp.looplen and loop_at is None and pos>=smp.looppos: loop_at=t
        if smp.looplen and loop_at is not None and t>=loop_at+max(1,math.ceil(smp.looplen/rate*60)): break
        typ,val,a=out; att=att_of(a)
        words.append((0x8000 if typ=='n' else 0)|(att<<11)|(val&0x3FF))
        t+=1
        if t>60*20: break
    if smp.looplen and loop_at is not None:
        words+=[0xFFFE,(len(words)-loop_at)*2+4]
    else: words.append(0xFFFF)
    b=struct.pack('<%dH'%len(words),*words)
    if len(sfxblob)//BANK != (len(sfxblob)+len(b)-1)//BANK: sfxblob+=b'\0'*(BANK-len(sfxblob)%BANK)
    ent.append((r,f,len(sfxblob))); sfxblob+=b
sb=place('SFX',sfxblob)
H.append('#define NSFX %d'%len(ent))
H.append('static const uint8_t sfx_tab[][5]={%s};'%','.join('{%d,%d,%d,0x%02X,0x%02X}'%(r,f,sb+o//BANK,(0x8000+o%BANK)&255,(0x8000+o%BANK)>>8) for r,f,o in ent))
align()
H.append('#define GAME_BANK_LAST %d'%(BANK0+len(blob)//BANK-1))
open('/home/claude/w/sms/gen/game.bin','wb').write(blob)
open('/home/claude/w/sms/gen/gamedata.h','w').write('\n'.join(H)+'\n')
print('game blob banks %d..%d, sfx %d entries (%d bytes), strings %s'%(BANK0,BANK0+len(blob)//BANK-1,len(ent),len(sfxblob),used))
