# Serialize encoded cutscenes + shared dictionary into ROM banks, emit fmv_data.h
import numpy as np, struct, pickle, sys
BANK=16384
def planar(key):
    a=np.frombuffer(key,np.uint8).reshape(8,8); out=bytearray()
    for row in a:
        for p in range(4):
            b=0
            for x in range(8): b|=((row[x]>>p)&1)<<(7-x)
            out.append(b)
    return bytes(out)
NT=[0x3800,0x3000]
def serialize(recs, tile_loc, end_tick):
    b=bytearray(); front=0
    for r in recs:
        back=1-front
        flags=1 if r['pal'] is not None else 0
        b+=struct.pack('<BH',flags,r['tick'])
        if flags: b+=bytes(r['pal'])
        b+=struct.pack('<H',len(r['uploads']))
        for s,i in r['uploads']:
            bk,ad=tile_loc[i]; b+=struct.pack('<HBH',0x4000|(s*32),bk,ad)
        cells=sorted(r['nt']); runs=[]
        for c,e in cells:
            if runs and runs[-1][0]+len(runs[-1][1])==c and len(runs[-1][1])<127: runs[-1][1].append(e)
            else: runs.append((c,[e]))
        b+=struct.pack('<H',len(runs))
        for c,es in runs:
            b+=struct.pack('<HB',0x4000|(NT[back]+c*2),len(es))
            for s,fl in es: b+=struct.pack('<H',s|((fl&1)<<9)|((fl&2)<<9))
        front=back
    b+=struct.pack('<BH',2,end_tick)
    return bytes(b)
def build(cuts, tiles, bank0, out_bin, out_h):
    """cuts: list of (name, recs, audio_bytes, end_tick). Layout: dictionary, then per cut video+audio streams."""
    blob=bytearray(); tile_loc={}
    per=BANK//32
    for i,k in enumerate(tiles):
        tile_loc[i]=(bank0+i//per,0x8000+(i%per)*32)
        blob+=planar(k)
    if len(blob)%BANK: blob+=b'\0'*(BANK-len(blob)%BANK)
    hdr=['/* generated by pack.py */','#define FMV_NCUTS %d'%len(cuts)]
    tab=[]
    for name,recs,audio,end_tick in cuts:
        v=serialize(recs,tile_loc,end_tick)
        vb=bank0+len(blob)//BANK; va=0x8000+len(blob)%BANK; blob+=v
        ab=bank0+len(blob)//BANK; aa=0x8000+len(blob)%BANK; blob+=audio
        tab.append((name,vb,va,ab,aa,len(v),len(audio)))
        hdr.append('#define FMV_%s %d'%(name.upper(),len(tab)-1))
    if len(blob)%BANK: blob+=b'\0'*(BANK-len(blob)%BANK)
    hdr.append('static const unsigned char fmv_tab[][6]={')
    for name,vb,va,ab,aa,lv,la in tab:
        hdr.append('  {%d,0x%02X,0x%02X,%d,0x%02X,0x%02X}, /* %s video %d B, audio %d B */'%(vb,va&255,va>>8,ab,aa&255,aa>>8,name,lv,la))
    hdr.append('};')
    hdr.append('#define FMV_BANK_FIRST %d\n#define FMV_BANK_LAST %d'%(bank0,bank0+len(blob)//BANK-1))
    open(out_bin,'wb').write(blob); open(out_h,'w').write('\n'.join(hdr)+'\n')
    print('fmv blob: %d banks (%d..%d), dict %d tiles'%(len(blob)//BANK,bank0,bank0+len(blob)//BANK-1,len(tiles)))
